import type { HoldingPreview, HoldingPreviewTotals } from "./holding-preview";

// K04 is a presentation-only step. These values mirror the design evidence and are not account data.
export const HOLDING_PREVIEWS = [
  {
    asset: "BTC",
    name: "Bitcoin",
    quantity: "0.350000",
    allocation: "35.21%",
    averageCost: "$61,450.00",
    currentPrice: "$67,542.21",
    change: "+2.41%",
    changeTone: "positive",
    marketValue: "$23,639.77",
    unrealizedPnl: "+$2,132.77",
    unrealizedPnlPercent: "+9.92%",
    pnlTone: "positive",
    isSmallBalance: false,
  },
  {
    asset: "ETH",
    name: "Ethereum",
    quantity: "2.500000",
    allocation: "28.91%",
    averageCost: "$3,102.50",
    currentPrice: "$3,412.67",
    change: "+1.85%",
    changeTone: "positive",
    marketValue: "$8,531.68",
    unrealizedPnl: "+$775.42",
    unrealizedPnlPercent: "+9.99%",
    pnlTone: "positive",
    isSmallBalance: false,
  },
  {
    asset: "SOL",
    name: "Solana",
    quantity: "15.000000",
    allocation: "20.31%",
    averageCost: "$142.50",
    currentPrice: "$155.87",
    change: "+3.27%",
    changeTone: "positive",
    marketValue: "$4,901.10",
    unrealizedPnl: "+$200.55",
    unrealizedPnlPercent: "+4.27%",
    pnlTone: "positive",
    isSmallBalance: false,
  },
  {
    asset: "ADA",
    name: "Cardano",
    quantity: "10,000.000000",
    allocation: "15.57%",
    averageCost: "$0.4520",
    currentPrice: "$0.4683",
    change: "-0.73%",
    changeTone: "negative",
    marketValue: "$1,932.02",
    unrealizedPnl: "-$162.90",
    unrealizedPnlPercent: "-7.78%",
    pnlTone: "negative",
    isSmallBalance: false,
  },
] satisfies readonly HoldingPreview[];

export const HOLDING_PREVIEW_TOTALS = {
  assetCount: 4,
  marketValue: "$38,004.57",
  unrealizedPnl: "+$2,945.84",
  unrealizedPnlPercent: "+8.41%",
  pnlTone: "positive",
} satisfies HoldingPreviewTotals;
